version: "3.9"
services:
  rarity-ui:
    build: .
    ports:
      - 3000
  nginx:
    image: nginx:latest
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - rarity-ui
    ports:
        - "80:80"